name: appdynamics_mobilesdk_example
description: Demonstrates how to use the appdynamics_mobilesdk plugin.
publish_to: 'none'
version: 2.0.3+2.0.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # global_configuration: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  appdynamics_mobilesdk:
    path: ../

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/settings.sample.json
