name: appdynamics_mobilesdk_example
description: Demonstrates how to use the appdynamics_mobilesdk plugin.
publish_to: 'none'
version: 0.0.2+0.0.2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  appdynamics_mobilesdk:
    path: ../

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
