include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: ignore
    must_be_immutable: ignore
  exclude:
    - android/**
    - ios/**

linter:
  rules:
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    always_use_package_imports: true
    annotate_overrides: true
    avoid_as: true
    avoid_catching_errors: true
    avoid_double_and_int_checks: true
    avoid_empty_else: true
    # - avoid_bool_literals_in_conditional_expressions
    # - avoid_equals_and_hash_code_on_mutable_classes
    # - avoid_escaping_inner_quotes
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_init_to_null: true
    avoid_js_rounded_ints: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: false
    avoid_print: false
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    # - avoid_setters_without_getters
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_web_libraries_in_flutter: true
    camel_case_extensions: true
    camel_case_types: true
    cancel_subscriptions: true
    # - cascade_invocations
    close_sinks: true
    constant_identifier_names: true
    control_flow_in_finally: true
    diagnostic_describe_all_properties: false #1к сообщений
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    file_names: true
    flutter_style_todos: true
    hash_and_equals: true
    implementation_imports: true
    iterable_contains_unrelated_type: true
    leading_newlines_in_multiline_strings: true
    library_names: true
    library_prefixes: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    lowercase_with_underscores: true
    missing_whitespace_between_adjacent_strings: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    no_runtimeType_toString: true
    non_constant_identifier_names: true
    omit_local_variable_types: false
    # - overridden_fields
    prefer_final_locals: true
    package_names: true
    package_prefixed_library_names: true
    # - parameter_assignments
    prefer_adjacent_string_concatenation: true
    prefer_const_declarations: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors_in_immutables: true
    # - prefer_const_literals_to_create_immutables
    # - prefer_constructors_over_static_methods
    # - prefer_function_declarations_over_variables
    # https://dart-lang.github.io/linter/lints/
    # - overridden_fields
    # - avoid_classes_with_only_static_members
    # - always_put_required_named_parameters_first
    # - always_put_control_body_on_new_line
    # - avoid_as
    # - avoid_catches_without_on_clauses
    prefer_const_constructors: true
    always_specify_types: true
    # - use_key_in_widget_constructors
    # - prefer_relative_imports # will produce thousand errors
    prefer_contains: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_foreach: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_spread_collections: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    recursive_getters: true
    slash_for_doc_comments: true
    sort_constructors_first: true
    sort_imports: true
    # sort_pub_dependencies: true
    # sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_statements: true
    unnecessary_string_interpolations: true
    unnecessary_this: false
    unrelated_type_equality_checks: true
    unsafe_html: true
    use_function_type_syntax_for_parameters: true
    valid_regexps: true
